test_suites:
    - name: e2e-classic
      script_path: /root/okta/samples-js-react/scripts/e2e
      sort_order: '1'
      timeout: '10'
      script_name: e2e-classic
      criteria: MERGE
      queue_name: small

    - name: e2e-oie
      script_path: /root/okta/samples-js-react/scripts/e2e
      sort_order: '1'
      timeout: '10'
      script_name: e2e-oie
      criteria: MERGE
      queue_name: small
